# Minimal Mistakes Configuration

# Theme Settings
remote_theme: "mmistakes/minimal-mistakes"
theme: null
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

# theme                  : "minimal-mistakes-jekyll"
# remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"


# Site Settings
locale: "en-US"
title: "Dr Charline Tessereau"
title_separator: "-"
name: "Charline Tessereau"
description: "Computational Neuroscientist and Data Scientist"
url: "https://charlinetess.github.io" # The base hostname & protocol for your site
baseurl: "" # The subpath of your site, e.g., "/blog"
show_recent_posts: false

header:
  show_title: false


# Author Settings
author:
  name: "Charline Tessereau"
  avatar: "/assets/images/avatar.png" # Path to your avatar image
  bio: "I am a **Computational Neuroscientist** and **Data Scientist** passionate about leveraging machine learning and data analysis to solve complex problems."
  location: "Tübingen, Germany"
  email: "tessereau.charline.at.gmail.com"
  # links:
  #   - label: "Email"
  #     icon: "fas fa-fw fa-envelope-square"
  #     url: "mailto:tessereau.charline@gmail.com"
  #   - label: "Google Scholar"
  #     icon: "fas fa-fw fa-link"
  #     url: "https://scholar.google.com/citations?user=XPTJG6wAAAAJ&hl=en&authuser=1"
  #   - label: "Twitter"
  #     icon: "fab fa-fw fa-twitter-square"
  #     url: "https://x.com/Charline_Tess"
  #   - label: "Bluesky"
  #     icon: "fab fa-fw fa-bluesky"
  #     url: "https://bsky.app/profile/chrltsr.bsky.social"
  #   - label: "GitHub"
  #     icon: "fab fa-fw fa-github"
  #     url: "https://github.com/charlinetess"
  #   - label: "LinkedIn"
  #     icon: "fab fa-fw fa-linkedin"
  #     url: "https://www.linkedin.com/in/charline-tessereau-457a95b8/"

# Navigation
navigation:
  - text: "Home"
    url: "/"
  - text: "CVs"
    url: "/cvs/"
  - text: "Research Interests"
    url: "/research-interests/"
  - text: "Applied Competences"
    url: "/applied-competences/"
  - text: "Publications"
    url: "/publications/"


# Social Links in Header/Footer
social_links:
  - icon: "google scholar"
    url: "https://scholar.google.com/citations?user=XPTJG6wAAAAJ&hl=en&authuser=1"

  - icon: "twitter"
    url: "https://x.com/Charline_Tess"

  - custom_html: |
      <a href="https://bsky.app/profile/chrltsr.bsky.social" target="_blank">
        <img src="/assets/images/bluesky.svg" alt="Bluesky" style="width:30px; height:30px;">
      </a>

  - icon: "github"
    url: "https://github.com/charlinetess"

  - icon: "linkedin"
    url: "https://www.linkedin.com/in/charline-tessereau-457a95b8/"


# SEO Settings
seo:
  title: "Dr Charline Tessereau | Computational Neuroscientist & Data Scientist"
  description: "Welcome to my professional website. I specialize in machine learning, data analysis, and computational neuroscience."

# Analytics
# analytics:
#   provider: "google" # Options: "google", "google-universal", "google-gtag", "custom"
#   google:
#     tracking_id: "YOUR_GOOGLE_ANALYTICS_TRACKING_ID" # Replace with your actual Tracking ID
#     anonymize_ip: true

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  # - jekyll-paginate
  - jekyll-gist
  - jekyll-include-cache


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path>/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path>/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

# Exclude Specific Files and Directories
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs
  - /test

# Include Specific Files and Directories
include:
  - .htaccess
  - _pages

# Encoding and Markdown Settings
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Kramdown Settings
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS Settings
sass:
  sass_dir: _sass
  style: compressed

# Permalink Structure
permalink: /:categories/:title/
timezone: "Europe/Berlin" # Replace with your timezone

# Pagination Settings
# paginate: 5
# paginate_path: /page:num/

custom_css:
  - "/assets/css/custom.css"



