# Minimal Mistakes Configuration

# Theme Settings
remote_theme: "mmistakes/minimal-mistakes"
theme: null

# Site Settings
locale: "en-US"
title: "Dr Charline Tessereau"
title_separator: "-"
name: "Charline Tessereau"
description: "Computational Neuroscientist and Data Scientist"
url: "https://charlinetess.github.io" # The base hostname & protocol for your site
baseurl: "" # The subpath of your site, e.g., "/blog"
show_recent_posts: false

# Hide site title in header
header:
  show_title: false

# Author Settings
author:
  name: "Charline Tessereau"
  avatar: "/assets/images/avatar.png"  # Ensure /assets/images/avatar.png exists
  bio: "I am a **Computational Neuroscientist** and **Data Scientist** passionate about leveraging machine learning and data analysis to solve complex problems."
  location: "Tübingen, Germany"
  email: "tessereau.charline.at.gmail.com"

# Navigation
navigation:
  - text: "Home"
    url: "/"
  - text: "Research Interests"
    url: "/research-interests/"
  - text: "Applied Competences"
    url: "/applied-competences/"
  - text: "CVs"
    url: "/cvs/"
  - text: "Publications"
    url: "/publications/"

# Social Links in Header/Footer
social_links:# Social Links in Header/Footer
social_links: []


# SEO
seo:
  title: "Dr Charline Tessereau | Computational Neuroscientist & Data Scientist"
  description: "Welcome to my professional website. I specialize in machine learning, data analysis, and computational neuroscience."

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-include-cache
  # Omitting jekyll-paginate => hides recent posts feature

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

# Exclusions
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs
  - /test

# Include
include:
  - .htaccess
  - _pages

# Markdown/SCSS Settings
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

sass:
  sass_dir: _sass
  style: compressed

permalink: /:categories/:title/
timezone: "Europe/Berlin"

# Custom SCSS to set Palatino
minimal_mistakes_skin: "default"
custom_css:
  - "/assets/css/custom-fonts.scss"
