# Minimal Mistakes Configuration

remote_theme: "mmistakes/minimal-mistakes"
theme: null

# Plugins recommended by Minimal Mistakes and used by your site
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-gist
  - jekyll-include-cache

# Site Settings
locale: "en-US"
title: "Dr Charline Tessereau"
title_separator: "-"
name: "Charline Tessereau"
description: "Computational Neuroscientist and Data Scientist"
url: "https://charlinetess.github.io"
baseurl: "" # The subpath of your site, e.g., "/blog"
show_recent_posts: false

# Hide the site title in the header (if you don't want the big text top-left)
header:
  show_title: false

# Author Settings
author:
  name: "Charline Tessereau"
  avatar: "/assets/images/avatar.png"
  bio: "I am a **Computational Neuroscientist** and **Data Scientist** passionate about leveraging machine learning and data analysis to solve complex problems."
  location: "Tübingen, Germany"
  email: "tessereau.charline.at.gmail.com"

# Navigation - the top bar links or optional side nav
# If you want to see these links across your site:
navigation:
  - text: "Home"
    url: "/"
  - text: "CVs"
    url: "/cvs/"
  - text: "Research Interests"
    url: "/research-interests/"
  - text: "Applied Competences"
    url: "/applied-competences/"
  - text: "Publications"
    url: "/publications/"
  - text: "Contact"
    url: "/contact/"

# Social Links in Header/Footer
social_links:
  - icon: "google scholar"
    url: "https://scholar.google.com/citations?user=XPTJG6wAAAAJ&hl=en&authuser=1"

  - icon: "twitter"
    url: "https://x.com/Charline_Tess"

  # Replace custom_html referencing local .svg with an actual external link
  # or do a custom icon approach. For quick fix, here's the correct link:
  - custom_html: |
      <a href="https://bsky.app/profile/chrltsr.bsky.social" target="_blank">
        <img src="https://img.icons8.com/ios-glyphs/30/000000/external-link.png" alt="Bluesky" style="width:30px; height:30px;">
      </a>

  - icon: "github"
    url: "https://github.com/charlinetess"

  - icon: "linkedin"
    url: "https://www.linkedin.com/in/charline-tessereau-457a95b8/"

# SEO Settings
seo:
  title: "Dr Charline Tessereau | Computational Neuroscientist & Data Scientist"
  description: "Welcome to my professional website. I specialize in machine learning, data analysis, and computational neuroscience."

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

# We don't want the Minimal Mistakes "Recent posts" or "Quick-Start" doc references
# => We'll handle that by removing references in layouts/data or simply ignoring them.

# Pagination
paginate: 5
paginate_path: "/page:num/"

# If you want to disable pagination entirely:
# remove `jekyll-paginate` from the plugins list
# and remove these lines:
pagination:
  debug: false
  collection: "posts"
  per_page: 5
  permalink: "/page/:num/"
  title: ":title - page :num"
  limit: 0
  sort_field: "date"
  sort_reverse: true

# Additional Font overrides or custom CSS
# We'll override the font in custom scss (below).
